server:
  port: 5104
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:5000/eureka/  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:
    #此实例注册到eureka服务端的唯一的实例ID，ip-address会自动拿到启动服务器的IP
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

spring:
  application:
    name: power-server #此实例注册到eureka服务端的name